export const ADD_NEW_TODO_REQUEST = 'ADD_NEW_TODO_REQUEST';
export const ADD_NEW_TODO_REQUEST_SUCCESS = 'ADD_NEW_TODO_REQUEST_SUCCESS';
export const ADD_NEW_TODO_REQUEST_FAILED = 'ADD_NEW_TODO_REQUEST_FAILED';

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';


export default null;